CREATE TABLE LOCALIDAD(
	CODLOCALIDAD NUMBER,
	NOMBRE VARCHAR(50),
	CODPROVINCIA NUMBER,
	CONSTRAINT cod_loc_pk PRIMARY KEY (CODLOCALIDAD),
	CONSTRAINT cod_pro_fk FOREIGN KEY (CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA)
);