CREATE TABLE EMPLEADO (
	ID NUMBER,
	DNI CHAR(9),
	NOMBRE VARCHAR(50),
	FECHANAC DATE,
	TELEFONO CHAR(12),
	SALARIO NUMBER,
	CODLOCALIDAD NUMBER,

	CONSTRAINT PRIMARY KEY (ID),
	CONSTRAINT UNIQUE (DNI),
 	CONSTRAINT FOREIGN KEY (CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD)
);