ALTER TABLE DEPARTAMENTOS ADD(
    CONSTRAINT dep_cen_fk FOREIGN KEY (numce) REFERENCES CENTROS(numce),
    CONSTRAINT dep_depde_fk FOREIGN KEY (depde) REFERENCES DEPARTAMENTOS(numde)
);
ALTER TABLE EMPLEADOS ADD(
    CONSTRAINT emp_depnum_fk FOREIGN KEY (numde) REFERENCES DEPARTAMENTOS(numde)
);
