CREATE TABLE DIRECTOR(
  NOMBRE VARCHAR2(20),
  NACIONALIDAD NACIONALIDAD(20),
);

ALTER TABLE DIRECTOR ADD(
  CONSTRAINT PK_NOMBRE_DIRE PRIMARY KEY (NOMBRE)
);

CREATE TABLE EJEMPLAR(
  ID_PELI NUMBER,
  NUMERO NUMBER,
  ESTADO VARCHAR2(20)
);

ALTER TABLE EJEMPLAR(
  CONSTRAINT PK_ID_NUM_EJEM PRIMARY KEY (ID_PELI, NUMERO),
  CONSTRAINT FK_ID_EJEM FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE PELICULA(
  ID NUMBER,
  TITULO VARCHAR2(20) NOT NULL,
  PRODUCTORA VARCHAR(20),
  NACIONALIDAD VARCHAR2(20),
  FECHA DATE,
  DIRECTOR VARCHAR(20)
);

ALTER TABLE PELICULA ADD(
  CONSTRAINT ID_PEL_pk PRIMARY KEY (ID),
  CONSTRAINT DIR_PEL_FK FOREIGN KEY (DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE ALQUILA(
  DNI CHAR(9),
  ID_PELI NUMBER,
  NUMERO NUMBER,
  FECHAALQUILER DATE,
  FECHADEVOLUCION DATE
);

ALTER TABLE ALQUILA ADD(
  CONSTRAINT COM_ALQ_pk PRIMARY KEY (DNI, ID_PELI, NUMERO, FECHAALQUILER),
  CONSTRAINT DNI_ALQ_fk FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
  CONSTRAINT IDNUM_ALQ_fk FOREIGN KEY (ID_PELI, NUMERO) REFERENCES EJEMPLAR(ID_PELI, NUMERO),
  CONSTRAINT FALQFDEV_ALQ_ck CHECK (FECHAALQUILER < FECHADEVOLUCION)
);

CREATE TABLE ACTUA (
  ACTOR VARCHAR2(20),
  ID_PELI NUMBER,
  PROTA CHAR(1) DEFAULT 'N'
);

ALTER TABLE ACTUA ADD(
  CONSTRAINT ACTID_ACT_pk PRIMARY KEY (ACTOR, ID_PELI),
  CONSTRAINT ACT_ACT_fk FOREIGN KEY (ACTOR) REFERENCES ACTORES(NOMBRE),
  CONSTRAINT ID_ACT_FK FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID),
  CONSTRAINT PROT_ACT_ck CHECK (PROTA IN('S','N'))
);

CREATE TABLE ACTORES (
  NOMBRE VARCHAR2(20),
  NACIONALIDAD VARCHAR2(20),
  SEXO CHAR(1)
);

ALTER TABLE ACTORES ADD(
  CONSTRAINT NOM_ACT_pk PRIMARY KEY (NOMBRE)
  CONSTRAINT SEX_ACT_ck CHECK (SEXO IN('H','M'))
);

CREATE TABLE SOCIO(
  DNI CHAR(9),
  NOMBRE VARCHAR2(20) NOT NULL,
  DIRECCION VARCHAR2(20),
  TELEFONO VARCHAR2(12),
  AVALADOR CHAR(9)
);

ALTER TABLE SOCIO ADD(
  CONSTRAINT DNI_SOC_pk PRIMARY KEY (DNI),
  CONSTRAINT AVA_SOC_fk FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);

