ALTER TABLE DIRECTOR ADD(
  CONSTRAINT PK_NOMBRE_DIRE PRIMARY KEY (NOMBRE)
);
ALTER TABLE PELICULA ADD(
  CONSTRAINT ID_PEL_pk PRIMARY KEY (ID),
  CONSTRAINT DIR_PEL_FK FOREIGN KEY (DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);
ALTER TABLE ACTORES ADD(
  CONSTRAINT NOM_ACT_pk PRIMARY KEY (NOMBRE)
  CONSTRAINT SEX_ACT_ck CHECK (SEXO IN('H','M'))
);
ALTER TABLE ACTUA ADD(
  CONSTRAINT ACTID_ACT_pk PRIMARY KEY (ACTOR, ID_PELI),
  CONSTRAINT ACT_ACT_fk FOREIGN KEY (ACTOR) REFERENCES ACTORES(NOMBRE),
  CONSTRAINT ID_ACT_FK FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID),
  CONSTRAINT PROT_ACT_ck CHECK (PROTA IN('S','N'))
);
ALTER TABLE SOCIO ADD(
  CONSTRAINT DNI_SOC_pk PRIMARY KEY (DNI),
  CONSTRAINT AVA_SOC_fk FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);
ALTER TABLE EJEMPLAR ADD(
  CONSTRAINT PK_ID_NUM_EJEM PRIMARY KEY (ID_PELI, NUMERO),
  CONSTRAINT FK_ID_EJEM FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);
ALTER TABLE ALQUILA ADD(
  CONSTRAINT COM_ALQ_pk PRIMARY KEY (DNI, ID_PELI, NUMERO, FECHAALQUILER),
  CONSTRAINT DNI_ALQ_fk FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
  CONSTRAINT IDNUM_ALQ_fk FOREIGN KEY (ID_PELI, NUMERO) REFERENCES EJEMPLAR(ID_PELI, NUMERO),
  CONSTRAINT FALQFDEV_ALQ_ck CHECK (FECHAALQUILER < FECHADEVOLUCION)
);


