CREATE TABLE ACTORES(
    NOMBRE VARCHAR2(20),
    NACIONALIDAD VARCHAR2(20),
    SEXO CHAR(1) DEFAULT 'H',
    CONSTRAINT ac_sex_ck CHECK (SEXO IN('H','M')),
    CONSTRAINT ac_nom_pk PRIMARY KEY (NOMBRE)
);